export const errors = {
    UNAUTHORIZED: 'You are not logged in',
    FORBIDDEN: "You don't have permission to do that",
    INVALID_PASSWORD: 'The password you entered is invalid.',
    INVALID_USERNAME: 'The username you entered is invalid.',
    INVALID_COOKIE_FORMAT: 'The cookie you entered is invalid. Make sure to paste your full cookie, including the warning message.',
    INVALID_COOKIE: 'The cookie you entered is invalid.',
    INVALID_ITEMS: 'The items you have are invalid.',
    EXPIRED_SESSION: 'You took too long to do that. Please try again.',
    INVALID_2FA: 'The 2FA code you entered is invalid.',
    ALREADY_LINKED: 'You already linked your Discord account.',
    NOT_LINKED: 'You need to link your Discord account to do that.',
    CAPTCHA_REQUIRED: 'You need to solve the captcha to continue.',
    JOINED_TOO_MANY_GIVEAWAYS: "You've joined too many giveaways recently, try again later",
    ALREADY_JOINED_GIVEAWAY: "You've already joined this giveaway",
    GIVEAWAY_NOT_FOUND: "The giveaway you're trying to join doesn't exist",
    CANNOT_JOIN_OWN_GIVEAWAY: "You can't join your own giveaway",
    INVALID_AMOUNT: 'The amount you entered is invalid.',
    INVALID_CAPTCHA: 'Invalid captcha. Try again.',
    CODE_ALREADY_EXISTS: 'This code is already being used.',
    CODE_NOT_FOUND: "This code doesn't exist",
    INSUFFICIENT_BALANCE: "You don't have enough balance to do that",
    ALREADY_STARTED: 'This game has already started.',
    NO_BOTS_AVAILABLE: 'There are no bots available to play.',
    ALREADY_IN_BATTLE: "You've already joined this battle",
    SLOT_TAKEN: 'This slot is already taken.',
    DISABLED: 'You cannot do this right now.',
    MAINTENANCE: 'This feature is disabled for maintenance.',
    NOT_FOUND: 'Not found.',
    LISTING_PENDING: 'Someone else is already buying this listing.',
    TOO_MANY_TRADES: "You've did too many trades recently, try again later",
    INVALID_ROBLOX_COOKIE: 'Your Roblox session expired. Please login again.',
    NOT_PREMIUM: 'You need to have Roblox premium to do that.',
    INVALID_TOTAL: 'The prices have updated. Please try again.',
    INVALID_CREDENTIALS: 'The username or password you entered is invalid.',
    INVALID_CODE: 'The code you entered is invalid.',
    MISSING_CODE: 'The code you entered is invalid.',
    AMOUNT_TOO_LOW: 'The amount you entered is too low.',
    ALREADY_AFFILIATED: 'You have already used an affiliate code.',
    NOT_ENOUGH_DEPOSITS: 'You need to deposit more to do this.',
    NOT_ENOUGH_BETS: 'You dont have enough affiliate earnings to claim.',
    GIVEAWAY_BANNED: "You can't join giveaways",
    SERVER_ERROR: "There was an error processing your request. Please try again later",
    INTERNAL_SERVER_ERROR: "There was an error processing your request. Please try again later",
    INTERNAL_ERROR: "There was an error processing your request. Please try again later",
    UNKNOWN_ERROR: "There was an error processing your request. Please try again later",
    EXCEEDED_MAX_TIP: "You've exceeded the maximum amount you are allowed to tip",
    PAGE_NOT_FOUND: "The page you're looking for doesn't exist",
    TRANSACTION_NOT_FOUND: "The transaction you're looking for doesn't exist",
    TRANSACTION_NOT_PENDING: "This transaction isn't pending",
    TRANSACTION_IN_PROGRESS: "This transaction is already being processed",
    INVALID_TOKEN: "The 2fa token you entered is invalid",
    PHRASE_ALREADY_EXISTS: 'This phrase already exists.',
    INVALID_PHRASE: 'Invalid phrase.',
    PHRASE_NOT_FOUND: 'Phrase not found.',
    INVALID_SEARCH: 'Invalid search.',
    GIVEAWAY_ENDED: 'Rain has already ended.',
    OUT_OF_BOUNDS: 'The amount you entered is out of bounds.',
    USER_NOT_FOUND: 'User not found.',
    INVALID_EARNINGS: 'Invalid earnings.',
    INVALID_ROLE: 'Invalid role.',
    CANNOT_SET_HIGHER_ROLE: 'You cannot set a role higher than your own.',
    CANNOT_EDIT_USER: 'You cannot edit this user.',
    SLOW_DOWN: 'Please wait a second before doing that again.',
    TOO_MANY_ATTEMPTS: 'You have tried too many times. Please try again later.',
    INSUFFICIENT_LEVEL: "You don't have a high enough level to do that",
    MISSING_DUMMY_ITEM: "You don't have a dummy item on your Roblox inventory. It has to be worth less than the listing price or R$200",
    SELLER_INVALID_ROBLOX_COOKIE: "This listing is not available anymore",
    SELLER_NOT_PREMIUM: "This listing is not available anymore",
    SELLER_INVALID_INVENTORY: "This listing is not available anymore",
    ITEM_ALREADY_LISTED: 'You already have a listing for this item.',
    ITEM_ON_HOLD: 'One of the items you are trying to sell is on hold.',
    INVALID_INVENTORY: 'Your inventory is out of sync. Try again.',
    AMOUNT_TOO_HIGH: 'The amount you entered is too high.',
    MISSING_ITEMS: 'Please select at least one item.',
    CANNOT_BUY_OWN_LISTING: "You can't buy your own listing",
    INSUFFICIENT_XP: "You need at least 5000 xp to be able to withdraw",
    SECURITY_QUESTION: "You aren't eligible to login using credentials. You can only login with cookie",
    AUTHENTICATOR_NOT_ENABLED: "You need to enable authenticator on your Roblox account to do that",
    LISTING_REMOVED: "This listing has been removed",
    ALREADY_USED_CODE: "You've already used this code",
    ROBLOX_ACCOUNT_AGE_AFFILIATE: "Your Roblox account needs to be at least 90 days old to use an affiliate code",
    CANT_REDEEM_OWN_CODE: "You can't redeem your own code",
    CODE_EXPIRED: "This code has reached it's maximum uses",
    SPONSOR_LOCK: "This feature is disabled for sponsored users",
    MIN_LISTING_PRICE: "Minimum listing price is 1 credits",
    PENDING_WITHDRAWAL: "You can only have one pending withdrawal at a time",
    EXCEEDED_MAX_CRYPTO: "This amount exceeds your maximum crypto withdrawal allowance",
    NOT_ENOUGH_WAGERED_CRYPTO: 'You need to wager at least 50% of your deposits to be able to withdraw crypto.',
    ACCOUNT_LOCKED: "Your account has been locked. Please contact support",
    HAS_PENDING_WITHDRAWAL: 'You already have a pending withdrawal.',
    INVALID_JOIN_AMOUNT: 'You need to join with a valid amount.',
    NOT_ENOUGH_GAMES: 'You need to play atleast one game.',
    CANNOT_TIP_SELF: 'You cannot tip yourself.',
    TOO_MANY_ITEMS: "You have selected too many items",
    INVALID_ITEM_AMOUNT: "You've reached the item limit",
    DIFFERENT_GAME_VALUES: "You can only use items from one game",
    GAME_CANCELLED: "This game has been cancelled",
    INVALID_ID: "This game does not exist",
    INVALID_ITEM_VALUE: "Minimum value for DAHOOD is 3000",
    USER_HAS_NO_RECENT_BET: "User hasn't placed a bet in the last 24 hours",
    TOO_SOON_TO_DELETE: "This coinflip is too recent",
    VALUE_TOO_HIGH: "Please join with a lower amount",
    ALREADY_JOINED: "You have already joined this game"
}